### ISSUE TITLE
assignment 1. - introduction

### ISSUE THREAD

**Issue by Bunoute** [C2DH/ranketwo#130]
"This is done through a technique known as optical character recognition (OCR), with software that is able to understand the meaning of the image of a character"

>> replace "meaning" with "content"?
"It considers these features:" >>> It considers for instance these features:

to conclude the introduction: "We now have a digitised newspaper: the image of the page and its text." 
>> add: "We will now dive into the practicalities of this transcription, how it works and what are the limits one should be aware of."

**Comment by stefaniascagliola** [comment]
I will change the sentence, because actually 'meaning' is also not correct, it should be plain: understand the image of a character. 

I will change into: ('for instance' does not sound correct in the middle of a sentence)
These are features that it can consider

The last sentence I will leave out, the text is already far too long for an introduction to an assignment,
