### ISSUE TITLE
standards for the following kinds of texts 

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#23]
we need protocols for:
- references to links (indent, hide in word, 
- titles of literature (italics?)

**Comment by danieleguido** [comment]
Ideally, literature should use the document yaml table in [_data/documents.yaml](https://github.com/C2DH/ranketwo/blob/master/_data/documents.yaml) and then referenced by their `slug` in units and assignments `contents`. We then have a unique way of rendering references everywhere in the website. @frederic-reis, check the js file: [assets/js/runtime.js](https://github.com/C2DH/ranketwo/blob/master/assets/js/runtime.js) to see how this it is supposed to happen. 

A quick example for @stefaniascagliola: in order to cite the paper *Towards A New Digital Historicism? Doing History in the Age of Abundance*, check the corresponding slug in the documents table [_data/documents.yaml](https://github.com/C2DH/ranketwo/blob/master/_data/documents.yaml), you will find: `fickers-towards-digital-historicism-age-abundance`. 
To cite in the text, you simply create a **markdown link** `[](fickers-towards-digital-historicism-age-abundance)` linking to the slug. The `runtime` script in the page will cite appropriately - we still have to decide teh citation style though...
