### ISSUE TITLE
Page not found on ranke2.uni.lu for skill training and expert meeting pages

### ISSUE THREAD

**Issue by frederic-reis** [C2DH/ranketwo#91]
@danieleguido 

I don't understand why these pages are not workings on the https://ranke2.uni.lu and work on https://c2dh.github.io/ranketwo

https://ranke2.uni.lu/define-dsc/skilltraining
https://ranke2.uni.lu/define-dsc/expert-meeting

**Comment by danieleguido** [comment]
Hi @frederic-reis 
the issue here is related to nginx configuration file.
Basically there was a directive which looked for the `skilltraining/index.html` page at the specific location; if none then looked for a `skilltraining.hmtl` file. I had to remove it because of the contact form, we should rewrite it correctly (with Jonathan?)

**Comment by frederic-reis** [comment]
I found the problem.
Because I didn't put a "/" at the end of the link and permalink metadata, Jekyll created the page `/define-dsc/skilltraining.html` instead of the page `/define-dsc/skilltraining/index.html`.

It's fixed.
